import { DEFAULT_TALUKAS } from './constants.js';

/**
 * In-Memory Data Store for Saurashtra (Gujarat) Agricultural Hubs & Produce
 */

export const mockUsers = [
  {
    _id: 'usr_farmer_01',
    fullName: 'Mansukhbhai Patel',
    phone: '9825012345',
    email: 'mansukh.patel@agriconnect.in',
    role: 'farmer',
    taluka: 'Gondal',
    district: 'Rajkot',
    state: 'Gujarat',
    kycStatus: 'verified',
    aadhaarMasked: 'XXXX-XXXX-1234',
    trustScore: 94,
  },
  {
    _id: 'usr_farmer_02',
    fullName: 'Pravinbhai Vala',
    phone: '9825054321',
    email: 'pravin.vala@agriconnect.in',
    role: 'farmer',
    taluka: 'Talala',
    district: 'Junagadh',
    state: 'Gujarat',
    kycStatus: 'verified',
    aadhaarMasked: 'XXXX-XXXX-5678',
    trustScore: 98,
  },
  {
    _id: 'usr_farmer_03',
    fullName: 'Hareshbhai Gohil',
    phone: '9825098765',
    email: 'haresh.gohil@agriconnect.in',
    role: 'farmer',
    taluka: 'Mahuva',
    district: 'Bhavnagar',
    state: 'Gujarat',
    kycStatus: 'verified',
    aadhaarMasked: 'XXXX-XXXX-9012',
    trustScore: 91,
  },
  {
    _id: 'usr_consumer_01',
    fullName: 'Jigneshbhai Shah',
    phone: '9898011223',
    email: 'jignesh.shah@gmail.com',
    role: 'consumer',
    taluka: 'Rajkot',
    district: 'Rajkot',
    state: 'Gujarat',
    kycStatus: 'verified',
    aadhaarMasked: 'XXXX-XXXX-4321',
    trustScore: 88,
  },
];

export const mockHubs = DEFAULT_TALUKAS.map((h, idx) => ({
  _id: `hub_${idx + 1}`,
  hubCode: h.talukaId,
  name: h.name,
  taluka: h.taluka,
  district: h.district,
  state: h.state,
  location: { latitude: h.latitude, longitude: h.longitude },
  capacityKg: h.capacityKg,
  currentLoadKg: h.currentLoadKg,
  farmersConnected: h.farmersConnected,
  status: h.status,
  specialty: h.specialty,
}));

export const mockProducts = [
  // --- OILSEEDS (તેલીબિયાં) ---
  {
    _id: 'prod_oil_01',
    name: 'Saurashtra Bold Groundnuts (સૌરાષ્ટ્ર મગફળી / GG-20)',
    category: 'Oilseeds',
    variety: 'GG-20 Saurashtra Bold',
    price: 75,
    unit: 'kg',
    availableQuantity: 2500,
    locationTaluka: 'Gondal, Rajkot',
    farmer: mockUsers[0],
    images: [{ url: 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&q=80&w=600', caption: 'High oil content Saurashtra groundnuts', isPrimary: true }],
    aiGrading: { qualityGrade: 'Grade A', confidenceScore: '96%', suggestedPriceRange: { min: 72, max: 80 }, marketTrend: '+5% steady demand' },
    isVerified: true,
    status: 'Available',
  },
  {
    _id: 'prod_oil_02',
    name: 'Organic White Sesame Seeds (સૌરાષ્ટ્ર સફેદ તલ / Til)',
    category: 'Oilseeds',
    variety: 'Gujarat Til-1 Premium',
    price: 145,
    unit: 'kg',
    availableQuantity: 800,
    locationTaluka: 'Amreli',
    farmer: mockUsers[2],
    images: [{ url: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&q=80&w=600', caption: 'Cleaned, pearl white sesame seeds', isPrimary: true }],
    aiGrading: { qualityGrade: 'Grade A', confidenceScore: '97%', suggestedPriceRange: { min: 140, max: 155 }, marketTrend: '+8% export surge' },
    isVerified: true,
    status: 'Available',
  },
  {
    _id: 'prod_oil_03',
    name: 'Black Mustard Seeds (સૌરાષ્ટ્ર કાળો રાયડો / Sarson)',
    category: 'Oilseeds',
    variety: 'Gujarat Mustard-3',
    price: 64,
    unit: 'kg',
    availableQuantity: 1200,
    locationTaluka: 'Junagadh',
    farmer: mockUsers[1],
    images: [{ url: 'https://images.unsplash.com/photo-1607672632458-9eb56696346b?auto=format&fit=crop&q=80&w=600', caption: 'High pungency pure black mustard', isPrimary: true }],
    aiGrading: { qualityGrade: 'Grade A', confidenceScore: '94%', suggestedPriceRange: { min: 60, max: 68 }, marketTrend: '+3% stable rate' },
    isVerified: true,
    status: 'Available',
  },

  // --- SPICES (મસાલા) ---
  {
    _id: 'prod_spc_01',
    name: 'Gondal Resham Patti Red Chillies (ગોંડલ લાલ મરચાં)',
    category: 'Spices',
    variety: 'Resham Patti Special Red',
    price: 240,
    unit: 'kg',
    availableQuantity: 1100,
    locationTaluka: 'Gondal, Rajkot',
    farmer: mockUsers[0],
    images: [{ url: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&q=80&w=600', caption: 'Sun-dried pure Gondal red chillies', isPrimary: true }],
    aiGrading: { qualityGrade: 'Grade A', confidenceScore: '95%', suggestedPriceRange: { min: 230, max: 255 }, marketTrend: '+8% high mandi rate' },
    isVerified: true,
    status: 'Available',
  },
  {
    _id: 'prod_spc_02',
    name: 'Organic Jamnagar Cumin Seeds (સૌરાષ્ટ્ર જીરું / Jeera)',
    category: 'Spices',
    variety: 'Gujarat Cumin-4 Special',
    price: 380,
    unit: 'kg',
    availableQuantity: 600,
    locationTaluka: 'Jamnagar Rural',
    farmer: mockUsers[1],
    images: [{ url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=600', caption: 'Aromatic unadulterated cumin seeds', isPrimary: true }],
    aiGrading: { qualityGrade: 'Grade A', confidenceScore: '98%', suggestedPriceRange: { min: 360, max: 410 }, marketTrend: '+12% peak mandi pricing' },
    isVerified: true,
    status: 'Available',
  },
  {
    _id: 'prod_spc_03',
    name: 'Saurashtra Green Coriander Seeds (લીલા સુકા ધાણા / Dhana)',
    category: 'Spices',
    variety: 'Gujarat Coriander-2',
    price: 110,
    unit: 'kg',
    availableQuantity: 950,
    locationTaluka: 'Gondal, Rajkot',
    farmer: mockUsers[0],
    images: [{ url: 'https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&q=80&w=600', caption: 'Bright green whole coriander seeds', isPrimary: true }],
    aiGrading: { qualityGrade: 'Grade A', confidenceScore: '93%', suggestedPriceRange: { min: 105, max: 120 }, marketTrend: '+4% steady demand' },
    isVerified: true,
    status: 'Available',
  },

  // --- GRAINS & CEREALS (અનાજ) ---
  {
    _id: 'prod_grn_01',
    name: 'Saurashtra Bhalia Sharbati Wheat (ભાલિયા દેશી ઘઉં)',
    category: 'Grains & Cereals',
    variety: 'Dawoodkhani Bhalia Gold',
    price: 52,
    unit: 'kg',
    availableQuantity: 3000,
    locationTaluka: 'Talala, Junagadh',
    farmer: mockUsers[1],
    images: [{ url: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=600', caption: 'Naturally rainfed Saurashtra Bhalia wheat', isPrimary: true }],
    aiGrading: { qualityGrade: 'Grade A', confidenceScore: '98%', suggestedPriceRange: { min: 50, max: 55 }, marketTrend: '+6% steady domestic demand' },
    isVerified: true,
    status: 'Available',
  },
  {
    _id: 'prod_grn_02',
    name: 'Saurashtra Desi Pearl Millet (સૌરાષ્ટ્ર દેશી બાજરો / Bajra)',
    category: 'Grains & Cereals',
    variety: 'GHB-558 Desi Sweet Bajra',
    price: 38,
    unit: 'kg',
    availableQuantity: 2100,
    locationTaluka: 'Gondal, Rajkot',
    farmer: mockUsers[0],
    images: [{ url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=600', caption: 'Sweet taste Saurashtra green pearl bajra', isPrimary: true }],
    aiGrading: { qualityGrade: 'Grade A', confidenceScore: '95%', suggestedPriceRange: { min: 36, max: 42 }, marketTrend: '+4% steady winter demand' },
    isVerified: true,
    status: 'Available',
  },
  {
    _id: 'prod_grn_03',
    name: 'Saurashtra White Jowar (સફેદ જુવાર / Sorghum)',
    category: 'Grains & Cereals',
    variety: 'GJ-38 Sweet Grain Jowar',
    price: 44,
    unit: 'kg',
    availableQuantity: 1400,
    locationTaluka: 'Junagadh',
    farmer: mockUsers[2],
    images: [{ url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&q=80&w=600', caption: 'Pest-free clean white jowar grain', isPrimary: true }],
    aiGrading: { qualityGrade: 'Grade A', confidenceScore: '92%', suggestedPriceRange: { min: 42, max: 48 }, marketTrend: '+3% steady health food demand' },
    isVerified: true,
    status: 'Available',
  },

  // --- PULSES & LEGUMES (કઠોળ) ---
  {
    _id: 'prod_pls_01',
    name: 'Saurashtra Organic Toor Dal (ગીર તુવેર દાળ / Pigeon Pea)',
    category: 'Pulses & Legumes',
    variety: 'Gujarat Tur-1 Desi',
    price: 138,
    unit: 'kg',
    availableQuantity: 1800,
    locationTaluka: 'Talala, Junagadh',
    farmer: mockUsers[1],
    images: [{ url: 'https://images.unsplash.com/photo-1585994192701-f1a505c8574a?auto=format&fit=crop&q=80&w=600', caption: 'Unpolished chemical-free Gir Toor Dal', isPrimary: true }],
    aiGrading: { qualityGrade: 'Grade A', confidenceScore: '96%', suggestedPriceRange: { min: 132, max: 145 }, marketTrend: '+9% strong retail demand' },
    isVerified: true,
    status: 'Available',
  },
  {
    _id: 'prod_pls_02',
    name: 'Desi Chana / Brown Chickpeas (સૌરાષ્ટ્ર દેશી ચણા / Gram)',
    category: 'Pulses & Legumes',
    variety: 'Gujarat Gram-4 Desi Bold',
    price: 68,
    unit: 'kg',
    availableQuantity: 2200,
    locationTaluka: 'Gondal, Rajkot',
    farmer: mockUsers[0],
    images: [{ url: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&q=80&w=600', caption: 'Uniform sized brown desi chickpeas', isPrimary: true }],
    aiGrading: { qualityGrade: 'Grade A', confidenceScore: '94%', suggestedPriceRange: { min: 65, max: 72 }, marketTrend: '+5% high MSP support' },
    isVerified: true,
    status: 'Available',
  },
  {
    _id: 'prod_pls_03',
    name: 'Green Moong Whole (લીલા દેશી આખા મગ / Mung Bean)',
    category: 'Pulses & Legumes',
    variety: 'Gujarat Moong-4 Shini',
    price: 92,
    unit: 'kg',
    availableQuantity: 1100,
    locationTaluka: 'Amreli',
    farmer: mockUsers[2],
    images: [{ url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=600', caption: 'Bright green nutritious whole moong', isPrimary: true }],
    aiGrading: { qualityGrade: 'Grade A', confidenceScore: '95%', suggestedPriceRange: { min: 88, max: 96 }, marketTrend: '+4% steady demand' },
    isVerified: true,
    status: 'Available',
  },

  // --- COTTON & CASH CROPS (કપાસ અને રોકડિયા પાક) ---
  {
    _id: 'prod_ctn_01',
    name: 'Saurashtra Shankar-6 Desi Cotton (શંકર-૬ સફેદ કપાસ)',
    category: 'Cotton & Cash Crops',
    variety: 'Shankar-6 Long Staple (28.5mm)',
    price: 135,
    unit: 'kg',
    availableQuantity: 4500,
    locationTaluka: 'Mahuva, Bhavnagar',
    farmer: mockUsers[2],
    images: [{ url: 'https://images.unsplash.com/photo-1606041008023-472dfb5e530f?auto=format&fit=crop&q=80&w=600', caption: 'Bright white staple Saurashtra Shankar cotton', isPrimary: true }],
    aiGrading: { qualityGrade: 'Grade A', confidenceScore: '95%', suggestedPriceRange: { min: 130, max: 142 }, marketTrend: '+7% spinning mill demand' },
    isVerified: true,
    status: 'Available',
  },
  {
    _id: 'prod_ctn_02',
    name: 'Amreli Long Staple Cotton Bales (સૌરાષ્ટ્ર કપાસ)',
    category: 'Cotton & Cash Crops',
    variety: 'G.Cot-23 Extra Long Staple',
    price: 142,
    unit: 'kg',
    availableQuantity: 3800,
    locationTaluka: 'Amreli',
    farmer: mockUsers[2],
    images: [{ url: 'https://images.unsplash.com/photo-1594897030560-69c1cf6ddc48?auto=format&fit=crop&q=80&w=600', caption: 'Top export grade white cotton staple', isPrimary: true }],
    aiGrading: { qualityGrade: 'Grade A', confidenceScore: '96%', suggestedPriceRange: { min: 138, max: 148 }, marketTrend: '+6% strong textile demand' },
    isVerified: true,
    status: 'Available',
  },
];

export const mockOrders = [
  {
    _id: 'ord_01',
    orderNumber: 'ORD-SAU-9102',
    buyer: mockUsers[3],
    farmer: mockUsers[1],
    items: [{ name: 'Saurashtra Bhalia Wheat (2 Quintal)', quantity: 2, unitPrice: 520, totalPrice: 1040 }],
    totalAmount: 1040,
    founderCommissionRate: 5,
    founderCommissionAmount: 52,
    netFarmerAmount: 988,
    escrowStatus: 'held_in_escrow',
    orderStatus: 'transit_to_hub',
    taluka: 'Talala, Junagadh',
  },
  {
    _id: 'ord_02',
    orderNumber: 'ORD-SAU-8421',
    buyer: mockUsers[3],
    farmer: mockUsers[0],
    items: [{ name: 'Gondal Red Chillies', quantity: 5, unitPrice: 240, totalPrice: 1200 }],
    totalAmount: 1200,
    founderCommissionRate: 5,
    founderCommissionAmount: 60,
    netFarmerAmount: 1140,
    escrowStatus: 'held_in_escrow',
    orderStatus: 'pooled_in_taluka',
    taluka: 'Gondal, Rajkot',
  },
];

export const mockTransparencies = {
  prod_01: {
    batchNumber: 'BATCH-WHEAT-2026',
    productName: 'Saurashtra Bhalia Sharbati Wheat',
    farmerName: 'Pravinbhai Vala',
    farmerTaluka: 'Talala, Junagadh (Gir Agro Hub)',
    harvestDate: 'Harvested 2 days ago',
    soilType: 'Rich Black Alluvial Soil (pH 7.2)',
    waterSource: 'Solar Powered Drip Irrigation & Rainfed Farm',
    isOrganicCertified: true,
    fertilizersUsed: [
      { name: 'Cow Manure & Gir Cow Panchamrit', type: 'Organic Compost' },
      { name: 'Jeevamrutha Bio-culture', type: 'Bio-fertilizer' },
    ],
    pesticideRecord: '100% Zero Synthetic Pesticides. Traditional neem decoction and agniastra.',
    coldChainTracking: [
      { checkpoint: 'Talala APMC Clean Grain Silo', temperatureCelsius: 22.0 },
      { checkpoint: 'Saurashtra Central Agro Logistics Hub', temperatureCelsius: 21.0 },
    ],
    farmLocationCoordinates: { latitude: 21.0500, longitude: 70.5200 },
    freshnessGuarantee: 'Cleaned, graded, moisture tested (<10%), zero foreign matter.',
  },
};
